apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidecar-dns-example
  name: sidecar-dns-example
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-dns-example
  template:
    metadata:
      labels:
        app: sidecar-dns-example
    spec:
      containers:
        - image: polarismesh/examples/sidecar-dns-example:v1.0.0
          imagePullPolicy: Always
          name: sidecar-dns-example
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: polarismesh/polaris-sidecar:v1.0.0
          imagePullPolicy: Always
          name: polaris-sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris-sidecar.yaml
              name: polaris-sidecar-config
              subPath: polaris-sidecar.yaml
            - mountPath: /root/polaris.yaml
              name: polaris-client-config
              subPath: polaris.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-sidecar-config
          name: polaris-sidecar-config
        - configMap:
            defaultMode: 420
            name: polaris-client-config
          name: polaris-client-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate