apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-sidecar-config
data:
  polaris-sidecar.yaml: |-
    bind: 0.0.0.0
    port: 53
    namespace: default
    polaris:
      addresses: 
        - 127.0.0.1
    recurse:
      enable: false
      timeoutSec: 1
    mtls:
      enable: false
    logger:
      output_paths:
        - stdout
      error_output_paths:
        - stderr
      rotate_output_path: logs/polaris-sidecar.log
      error_rotate_output_path: logs/polaris-sidecar-error.log
      rotation_max_size: 100
      rotation_max_backups: 10
      rotation_max_age: 7
      output_level: info
    resolvers:
      - name: dnsagent
        dns_ttl: 10
        enable: true
        suffix: "."
        # option:
        #   route_labels: "key:value,key:value"
      - name: meshproxy
        dns_ttl: 120
        enable: false
        option:
          reload_interval_sec: 30
          dns_answer_ip: 10.4.4.4
          recursion_available: true
