apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-client-config
data:
  polaris.yaml: |-
    global:
      serverConnector:
        addresses:
          - 127.0.0.1:8091
      location:
        provider: tencent