---
apiVersion: v1
kind: Service
metadata:
  name: polaris-sidecar-dns
  labels:
    app: polaris-sidecar-dns
spec:
  type: LoadBalancer
  ports:
    - port: 53
      protocol: TCP
      name: dns-tcp-server
      targetPort: 53
    - port: 53
      protocol: UDP
      name: dns-udp-server
      targetPort: 53
  selector:
    app: polaris-sidecar-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polaris-sidecar-dns
  name: polaris-sidecar-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polaris-sidecar-dns
  template:
    metadata:
      labels:
        app: polaris-sidecar-dns
    spec:
      containers:
        - image: polarismesh/polaris-sidecar:latest
          imagePullPolicy: Always
          name: polaris-sidecar
          command: ["./polaris-sidecar"]
          args:
            - start
            - -p
            - "53"
            - -r
            - "false"
            - -d
            - "true"
            - -m
            - "false"
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /data/polaris.yaml
              name: polaris-client-config
              subPath: polaris.yaml
            - mountPath: /data/polaris-sidecar.yaml
              name: polaris-sidecar-config
              subPath: polaris-sidecar.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-client-config
          name: polaris-client-config
        - configMap:
            defaultMode: 420
            name: polaris-sidecar-config
          name: polaris-sidecar-config
