---
apiVersion: v1
kind: Service
metadata:
  name: polaris-sidecar-dns
  labels:
    app: polaris-sidecar-dns
spec:
  type: LoadBalancer
  ports:
    - port: 53
      protocol: TCP
      name: dns-tcp-server
      targetPort: 53
    - port: 53
      protocol: UDP
      name: dns-udp-server
      targetPort: 53
  selector:
    app: polaris-sidecar-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polaris-sidecar-dns
  name: polaris-sidecar-dns
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: polaris-sidecar-dns
  template:
    metadata:
      labels:
        app: polaris-sidecar-dns
    spec:
      containers:
        - image: polarismesh/polaris-sidecar:lastest
          imagePullPolicy: Always
          name: polaris-sidecar
          args:
            - start
            - -p
            - "53"
            - -r
            - "false"
            - -d
            - "true"
            - -m
            - "false"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris.yaml
              name: polaris-client-config
              subPath: polaris.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-client-config
          name: polaris-client-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate